### PR TITLE
Build fixups for version 2.1.2

### PR DESCRIPTION
**Pull request by aszlig**
Version 2.1.2 has introduced a few issues (eg. #10, #11) which particularly surface on non-NixOS systems. This branch should essentially fix building the library/executable as position-independent code and also fix our linker script.

All those issues were introduced with 8e10ef2d1d76ba8835735eaab167e77de34df88a.

Hydra jobset: https://headcounter.org/hydra/jobset/ip2unix/build-fixups
Cc: @etam

### CODE REVIEW

**Comment by aszlig** [comment]
@etam: Can you please check whether `ip2unix` works with these fixes?

**Comment by etam** [comment]
:+1:

**Comment by aszlig** [comment]
> +1

I hope this means that it's working. :-)

Added another fix (and regression test) for the linker script which was actually being passed to *cflags* instead of *ldflags* and thus not working. Can you please check whether the fix works for you as well?

**Comment by etam** [comment]
Yes it works. I had one unrelated spurious SIGSEGV in test_globpath. See #15.

**Pull request merged**
